version: '3.8'

services:
   db:
      image: postgres:17.2
      container_name: tata-test-db
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: ms-movements
      ports:
        - '5432:5432'
   app:
     image: ms-movements:1.0
     container_name: tata-test-app
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ms-movements
       SPRING_DATASOURCE_USERNAME: admin
       SPRING_DATASOURCE_PASSWORD: secret
       SPRING_JPA_HIBERNATE_DDL_AUTO: update
     depends_on:
       - database
     ports:
       - '8080:8080'
     networks:
       - app_network
networks:
  app_network:
    driver: bridge

volumes:
  db_data: