version: '3.8' 

services:
  app:
    container_name: ms-movements-app
    image: ms-movements:lastest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/ms-movements
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=secret
    depends_on:
      - db

  db:
    container_name: ms-movements-db
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ms-movements
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret